sudo: required
dist: trusty
language: node_js
node_js:
- '9'

jobs:
  include:
    - stage: test
      addons:
        chrome: 'stable'

      before_install:
      - export CHROME_BIN=google-chrome-stable
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start

      before_script:
      - yarn global add angular-cli
      - yarn install
      - ng build

      script:
      - ng test --watch false
      - ng e2e

    - stage: deploy
      if: branch = master and type = push
      install:
      script:
      - docker build
            --file "Dockerfile"
            --tag "brianmay/spud-client:latest"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "brianmay/spud-client:latest"
      - ./deploy.sh
