sudo: required
dist: trusty
language: node_js
node_js:
- '9'

addons:
  chrome: 'stable'

before_install:
- export CHROME_BIN=google-chrome-stable
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- yarn global add angular-cli
- yarn install
- ng build

script:
- ng test --watch false
- ng e2e
