version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: |
          yarn global add angular-cli
          yarn install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: yarn ng -- build --no-progress
      - run: yarn test --  --watch false
      - run: yarn e2e

  deploy-prod:
    docker:
      - image: circleci/node:9
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build \
            --file "Dockerfile" \
            --tag "brianmay/spud-client:latest" \
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg "VCS_REF=$CIRCLE_SHA1" \
            .
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          docker push "brianmay/spud-client:latest"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          context: Docker
          requires:
            - build
          filters:
            branches:
              only: master
